Ignore comment lines when parsing config files.
* libs/config.bash.in (store_config): Ignore comment lines in
config files and make parsing more robust, bug 598480.

diff --git a/libs/config.bash.in b/libs/config.bash.in
--- a/libs/config.bash.in
+++ b/libs/config.bash.in
@@ -57,9 +57,11 @@ store_config() {
 		# parse the names of all settings in the file
 		local ifs_save=${IFS} IFS=$'\n'
 		for line in ${content} ; do
-			[[ ${line/=/} != ${line} ]] || continue
-			line=${line/=*/}
-			local ${line}=""
+			line=${line##*([[:space:]])}
+			[[ ${line} != "#"* && ${line} == *=* ]] || continue
+			line=${line%%=*}
+			# assignment will fail if ${line} is not a valid identifier
+			local ${line}="" || continue
 			vars=(${vars[@]} ${line})
 		done
 		IFS=${ifs_save}
