Rename local variable PREFIX to prefix.
svn path=/trunk/; revision=731

diff --git a/libs/skel.bash.in b/libs/skel.bash.in
--- a/libs/skel.bash.in
+++ b/libs/skel.bash.in
@@ -293,18 +293,18 @@ do_add() {
 
 	# If $D is set, we're adding from portage so we want to respect sandbox.
 	# Otherwise, respect the ROOT variable.
-	local PREFIX=${D:-${EROOT}}
+	local prefix=${D:-${EROOT}}
 
 	# Create directory if necessary
-	if [[ ! -e ${PREFIX}/etc/env.d/${IFACE}/${1} ]]; then
-		mkdir -p "${PREFIX}/etc/env.d/${IFACE}/${1}"
+	if [[ ! -e ${prefix}/etc/env.d/${IFACE}/${1} ]]; then
+		mkdir -p "${prefix}/etc/env.d/${IFACE}/${1}"
 	else
-		if [[ ! -d ${PREFIX}/etc/env.d/${IFACE}/${1} ]]; then
-			die -q "${PREFIX}/etc/env.d/${IFACE}/${1} exists but isn't a directory!"
+		if [[ ! -d ${prefix}/etc/env.d/${IFACE}/${1} ]]; then
+			die -q "${prefix}/etc/env.d/${IFACE}/${1} exists but isn't a directory!"
 		fi
 	fi
 
-	if ! cp ${2} "${PREFIX}/etc/env.d/${IFACE}/${1}/${3}"; then
-		die -q "Installing ${2} as ${PREFIX}/etc/env.d/${IFACE}/${1}/${3} failed!"
+	if ! cp ${2} "${prefix}/etc/env.d/${IFACE}/${1}/${3}"; then
+		die -q "Installing ${2} as ${prefix}/etc/env.d/${IFACE}/${1}/${3} failed!"
 	fi
 }
