Substitute prefix, datadir and sysconfdir in libs/Makefile.am; make use of it in skel.bash.in. Add case patterns for ppc-macos in package-manager.bash.in.
svn path=/trunk/; revision=534

diff --git a/libs/skel.bash.in b/libs/skel.bash.in
--- a/libs/skel.bash.in
+++ b/libs/skel.bash.in
@@ -1,4 +1,4 @@
-# Copyright 1999-2006 Gentoo Foundation
+# Copyright 1999-2009 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Id$
 
@@ -18,14 +18,14 @@
 # a comment. One caveat about the symlink map -- instead of using "lib" or
 # "lib64" etc, you must use @LIBDIR@.
 
-inherit config multilib portage tests
+inherit config multilib tests
 
 # find_implems $iface $libdir
 # find all possible implems for $libdir
 find_implems() {
     local -a implems
     iface=$1 libdir=$2
-    for file in ${ROOT}/etc/env.d/${iface}/${libdir}/* ; do
+    for file in ${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/* ; do
         [[ -f ${file} ]] || continue
         [[ "${file##*/}" != "config" ]] || continue
         implems=(${implems[@]} "${file##*/}")
@@ -37,7 +37,7 @@ find_implems() {
 # returns true if $implem is currently used for the $iface/$libdir combination
 is_active() {
     [[ ${#@} -eq 3 ]] || die "Need exactly 3 arguments!"
-    current=$(load_config ${ROOT}/etc/env.d/${1}/${2}/config CURRENT)
+    current=$(load_config ${ROOT}@sysconfdir@/env.d/${1}/${2}/config CURRENT)
     [[ ${current} == ${3} ]]
 }
 
@@ -49,9 +49,10 @@ switch_implem() {
     local iface=${1}
     local libdir=${2}
     local implem=${3##*/}
-    local implem_file="${ROOT}/etc/env.d/${iface}/${libdir}/${implem}"
-    local current=$(load_config "${ROOT}"/etc/env.d/${iface}/${libdir}/config CURRENT)
-    local current_file="${ROOT}/etc/env.d/${iface}/${libdir}/${current}"
+    local implem_file=${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/${implem}
+    local current=$(load_config \
+        "${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/config" CURRENT)
+    local current_file=${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/${current}
     local dest src
 
     # Get rid of old symlinks, if we have a current config
@@ -82,7 +83,7 @@ switch_implem() {
     done < ${implem_file}
 
     store_config \
-        "${ROOT}"/etc/env.d/${iface}/${libdir}/config \
+        "${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/config" \
         CURRENT ${implem}
 }
 
@@ -112,15 +113,16 @@ iface_do_list() {
 # Shows the current implementation for $libdir
 iface_do_show() {
     local iface=$IFACE libdir=$1 implem
-    config=${ROOT}/etc/env.d/${iface}/${libdir}/config
+    config=${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/config
     [[ ${#config[@]} -eq 1 ]] \
         || return
     [[ -e ${config} ]] \
         || return
 
-    implem=$(load_config ${ROOT}/etc/env.d/${iface}/${libdir}/config CURRENT)
-    [[ -e ${ROOT}/etc/env.d/${iface}/${libdir}/${implem} ]] \
-        || die "File \"${ROOT}/etc/env.d/${iface}/${libdir}/${implem}\" is missing!"
+    implem=$(load_config \
+        "${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/config" CURRENT)
+    [[ -e ${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/${implem} ]] \
+        || die "File \"${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/${implem}\" is missing!"
 
     echo "${libdir}: ${implem}"
 }
@@ -144,8 +146,8 @@ do_list() {
     local i=0
 
     for libdir in $(get_libdirs); do
-        [[ -d ${ROOT}/usr/${libdir} ]] \
-            && [[ ! -h ${ROOT}/usr/${libdir} ]] \
+        [[ -d ${ROOT}@prefix@/${libdir} ]] \
+            && [[ ! -h ${ROOT}@prefix@/${libdir} ]] \
             || continue
         iface_do_list $libdir
     done
@@ -262,8 +264,8 @@ do_show() {
     [[ -n ${mylibdirs[@]} ]] && libdirs=${mylibdirs[@]}
 
     for libdir in ${libdirs}; do
-        [[ -d ${ROOT}/usr/${libdir} ]] \
-            && [[ ! -h ${ROOT}/usr/${libdir} ]] \
+        [[ -d ${ROOT}@prefix@/${libdir} ]] \
+            && [[ ! -h ${ROOT}@prefix@/${libdir} ]] \
             || continue
         iface_do_show $libdir
     done
@@ -294,16 +296,16 @@ do_add() {
     local PREFIX=${D:-${ROOT}}
 
     # Create directory if necessary
-    if [[ ! -e ${PREFIX}/etc/env.d/${IFACE}/${1} ]]; then
-        mkdir -p ${PREFIX}/etc/env.d/${IFACE}/${1}
+    if [[ ! -e ${PREFIX}@sysconfdir@/env.d/${IFACE}/${1} ]]; then
+        mkdir -p "${PREFIX}@sysconfdir@/env.d/${IFACE}/${1}"
     else
-        if [[ ! -d ${PREFIX}/etc/env.d/${IFACE}/${1} ]]; then
-            die -q "${PREFIX}/etc/env.d/${IFACE}/${1} exists but isn't a directory!"
+        if [[ ! -d ${PREFIX}@sysconfdir@/env.d/${IFACE}/${1} ]]; then
+            die -q "${PREFIX}@sysconfdir@/env.d/${IFACE}/${1} exists but isn't a directory!"
         fi
     fi
 
-    if ! cp ${2} ${PREFIX}/etc/env.d/${IFACE}/${1}/${3}; then
-        die -q "Installing ${2} as ${PREFIX}/etc/env.d/${IFACE}/${1}/${3} failed!"
+    if ! cp ${2} "${PREFIX}@sysconfdir@/env.d/${IFACE}/${1}/${3}"; then
+        die -q "Installing ${2} as ${PREFIX}@sysconfdir@/env.d/${IFACE}/${1}/${3} failed!"
     fi
 }
 
