Revert some changes of 2009-05-15.
svn path=/trunk/; revision=607

diff --git a/libs/skel.bash.in b/libs/skel.bash.in
--- a/libs/skel.bash.in
+++ b/libs/skel.bash.in
@@ -37,7 +37,7 @@ inherit config multilib tests
 find_implems() {
 	local -a implems
 	iface=$1 libdir=$2
-	for file in ${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/* ; do
+	for file in ${ROOT}/etc/env.d/${iface}/${libdir}/* ; do
 		[[ -f ${file} ]] || continue
 		[[ "${file##*/}" != "config" ]] || continue
 		implems=(${implems[@]} "${file##*/}")
@@ -49,7 +49,7 @@ find_implems() {
 # returns true if $implem is currently used for the $iface/$libdir combination
 is_active() {
 	[[ ${#@} -eq 3 ]] || die "Need exactly 3 arguments!"
-	current=$(load_config ${ROOT}@sysconfdir@/env.d/${1}/${2}/config CURRENT)
+	current=$(load_config ${ROOT}/etc/env.d/${1}/${2}/config CURRENT)
 	[[ ${current} == ${3} ]]
 }
 
@@ -61,10 +61,10 @@ switch_implem() {
 	local iface=${1}
 	local libdir=${2}
 	local implem=${3##*/}
-	local implem_file=${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/${implem}
+	local implem_file=${ROOT}/etc/env.d/${iface}/${libdir}/${implem}
 	local current=$(load_config \
-		"${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/config" CURRENT)
-	local current_file=${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/${current}
+		"${ROOT}/etc/env.d/${iface}/${libdir}/config" CURRENT)
+	local current_file=${ROOT}/etc/env.d/${iface}/${libdir}/${current}
 	local dest src
 
 	# Get rid of old symlinks, if we have a current config
@@ -95,7 +95,7 @@ switch_implem() {
 	done < ${implem_file}
 
 	store_config \
-		"${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/config" \
+		"${ROOT}/etc/env.d/${iface}/${libdir}/config" \
 		CURRENT ${implem}
 }
 
@@ -123,16 +123,15 @@ iface_do_list() {
 # Shows the current implementation for $libdir
 iface_do_show() {
 	local iface=$IFACE libdir=$1 implem
-	config=${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/config
+	config=${ROOT}/etc/env.d/${iface}/${libdir}/config
 	[[ ${#config[@]} -eq 1 ]] \
 		|| return
 	[[ -e ${config} ]] \
 		|| return
 
-	implem=$(load_config \
-		"${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/config" CURRENT)
-	[[ -e ${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/${implem} ]] \
-		|| die "File \"${ROOT}@sysconfdir@/env.d/${iface}/${libdir}/${implem}\" is missing!"
+	implem=$(load_config "${ROOT}/etc/env.d/${iface}/${libdir}/config" CURRENT)
+	[[ -e ${ROOT}/etc/env.d/${iface}/${libdir}/${implem} ]] \
+		|| die "File \"${ROOT}/etc/env.d/${iface}/${libdir}/${implem}\" is missing!"
 
 	echo "${libdir}: ${implem}"
 }
@@ -156,8 +155,8 @@ do_list() {
 	local i=0
 
 	for libdir in $(get_libdirs); do
-		[[ -d ${ROOT}@prefix@/${libdir} ]] \
-			&& [[ ! -h ${ROOT}@prefix@/${libdir} ]] \
+		[[ -d ${ROOT}/usr/${libdir} ]] \
+			&& [[ ! -h ${ROOT}/usr/${libdir} ]] \
 			|| continue
 		iface_do_list $libdir
 	done
@@ -274,8 +273,8 @@ do_show() {
 	[[ -n ${mylibdirs[@]} ]] && libdirs=${mylibdirs[@]}
 
 	for libdir in ${libdirs}; do
-		[[ -d ${ROOT}@prefix@/${libdir} ]] \
-			&& [[ ! -h ${ROOT}@prefix@/${libdir} ]] \
+		[[ -d ${ROOT}/usr/${libdir} ]] \
+			&& [[ ! -h ${ROOT}/usr/${libdir} ]] \
 			|| continue
 		iface_do_show $libdir
 	done
@@ -306,16 +305,16 @@ do_add() {
 	local PREFIX=${D:-${ROOT}}
 
 	# Create directory if necessary
-	if [[ ! -e ${PREFIX}@sysconfdir@/env.d/${IFACE}/${1} ]]; then
-		mkdir -p "${PREFIX}@sysconfdir@/env.d/${IFACE}/${1}"
+	if [[ ! -e ${PREFIX}/etc/env.d/${IFACE}/${1} ]]; then
+		mkdir -p "${PREFIX}/etc/env.d/${IFACE}/${1}"
 	else
-		if [[ ! -d ${PREFIX}@sysconfdir@/env.d/${IFACE}/${1} ]]; then
-			die -q "${PREFIX}@sysconfdir@/env.d/${IFACE}/${1} exists but isn't a directory!"
+		if [[ ! -d ${PREFIX}/etc/env.d/${IFACE}/${1} ]]; then
+			die -q "${PREFIX}/etc/env.d/${IFACE}/${1} exists but isn't a directory!"
 		fi
 	fi
 
-	if ! cp ${2} "${PREFIX}@sysconfdir@/env.d/${IFACE}/${1}/${3}"; then
-		die -q "Installing ${2} as ${PREFIX}@sysconfdir@/env.d/${IFACE}/${1}/${3} failed!"
+	if ! cp ${2} "${PREFIX}/etc/env.d/${IFACE}/${1}/${3}"; then
+		die -q "Installing ${2} as ${PREFIX}/etc/env.d/${IFACE}/${1}/${3} failed!"
 	fi
 }
 
